devices:
  - id: 1
    type: "net"
    mmio_addr: 0xa003e00
    data_plane: virtio
    tap_name: "tap0"
    mac_addr: "52:54:00:aa:bb:01"
  - id: 2
    type: "block"
    mmio_addr: 0xa003c00
    data_plane: virtio
    file_path: "/etc/ext4_frontend_vm1_image.img"
    read_only: false
    root_device: true
    advertise_flush: false
